version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - waffle
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST="localhost"
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - waffle

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  waffle:
    driver: bridge